language: python
python:
  - "3.6"

services:
  - docker

before_script: pip3 install docker-compose

script:
  - docker-compose run app sh -c "python3 manage.py wait_for_db && python manage.py test && flake8"
